config/routes.rb
Tuntun::Application.routes.draw do
  scope '/api' do
    resources :websites
  end

end

app/models/website.rb
class Website < ActiveRecord::Base
end

app/models/website_history.rb
class WebsiteHistory < ActiveRecord::Base
  belongs_to :website
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/website_histories_controller.rb
class WebsiteHistoriesController < ApplicationController
  before_action :set_website_history, only: [:show, :edit, :update, :destroy]

  # GET /website_histories
  # GET /website_histories.json
  def index
    @website_histories = WebsiteHistory.all
  end

  # GET /website_histories/1
  # GET /website_histories/1.json
  def show
  end

  # GET /website_histories/new
  def new
    @website_history = WebsiteHistory.new
  end

  # GET /website_histories/1/edit
  def edit
  end

  # POST /website_histories
  # POST /website_histories.json
  def create
    @website_history = WebsiteHistory.new(website_history_params)

    respond_to do |format|
      if @website_history.save
        format.html { redirect_to @website_history, notice: 'Website history was successfully created.' }
        format.json { render action: 'show', status: :created, location: @website_history }
      else
        format.html { render action: 'new' }
        format.json { render json: @website_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /website_histories/1
  # PATCH/PUT /website_histories/1.json
  def update
    respond_to do |format|
      if @website_history.update(website_history_params)
        format.html { redirect_to @website_history, notice: 'Website history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @website_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /website_histories/1
  # DELETE /website_histories/1.json
  def destroy
    @website_history.destroy
    respond_to do |format|
      format.html { redirect_to website_histories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website_history
      @website_history = WebsiteHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_history_params
      params.require(:website_history).permit(:website_id, :success, :body)
    end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render action: 'show', status: :created, location: @website }
      else
        format.html { render action: 'new' }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuntun</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/website_histories/_form.html.erb
<%= form_for(@website_history) do |f| %>
  <% if @website_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website_history.errors.count, "error") %> prohibited this website_history from being saved:</h2>

      <ul>
      <% @website_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :website_id %><br>
    <%= f.text_field :website_id %>
  </div>
  <div class="field">
    <%= f.label :success %><br>
    <%= f.check_box :success %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/website_histories/edit.html.erb
<h1>Editing website_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @website_history %> |
<%= link_to 'Back', website_histories_path %>

app/views/website_histories/index.html.erb
<h1>Listing website_histories</h1>

<table>
  <thead>
    <tr>
      <th>Website</th>
      <th>Success</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @website_histories.each do |website_history| %>
      <tr>
        <td><%= website_history.website %></td>
        <td><%= website_history.success %></td>
        <td><%= website_history.body %></td>
        <td><%= link_to 'Show', website_history %></td>
        <td><%= link_to 'Edit', edit_website_history_path(website_history) %></td>
        <td><%= link_to 'Destroy', website_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website history', new_website_history_path %>

app/views/website_histories/new.html.erb
<h1>New website_history</h1>

<%= render 'form' %>

<%= link_to 'Back', website_histories_path %>

app/views/website_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Website:</strong>
  <%= @website_history.website %>
</p>

<p>
  <strong>Success:</strong>
  <%= @website_history.success %>
</p>

<p>
  <strong>Body:</strong>
  <%= @website_history.body %>
</p>

<%= link_to 'Edit', edit_website_history_path(@website_history) %> |
<%= link_to 'Back', website_histories_path %>

app/views/websites/_form.html.erb
<%= form_for(@website) do |f| %>
  <% if @website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% @website.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing website</h1>

<%= render 'form' %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<h1>Listing websites</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.url %></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %>

app/views/websites/new.html.erb
<h1>New website</h1>

<%= render 'form' %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>